### ISSUE TITLE
bottom line :)

### ISSUE THREAD

**Issue by H0neymOOn** [DakshHandeCode/LichessInsightHub#11]
![Screenshot (1128)](https://github.com/DakshHandeCode/LichessInsightHub/assets/156373912/83061a8b-409e-47a3-8fb8-929f79538987)

do you see "my bottom line" ? :)

**Comment by DakshHandeCode** [comment]
Thanks for the issue you noticed on the website , we will fix that right away just give us some time @H0neymOOn

**Comment by H0neymOOn** [comment]
as wished:
![Screenshot (1131)](https://github.com/DakshHandeCode/LichessInsightHub/assets/156373912/58b855ee-7d84-4c7a-a21a-68546e807c71)

![Screenshot (1132)](https://github.com/DakshHandeCode/LichessInsightHub/assets/156373912/3576d9c3-49c5-4165-ba7a-2554b3776988)

![Screenshot (1134)](https://github.com/DakshHandeCode/LichessInsightHub/assets/156373912/b700af84-499e-4d44-8215-404585fd3f41)

**Comment by HeXqqCode** [comment]
You're issue has been fixed check the website now . We've added a new stuff which will fix you're issue

**Comment by DakshHandeCode** [comment]
Issue resolved you can re check the website
