### ISSUE TITLE
Want to be able scrolling down reading whole part of last segment "Lichess AppealbSystem"

### ISSUE THREAD

**Issue by H0neymOOn** [DakshHandeCode/LichessInsightHub#9]
https://dakshhandecode.github.io/LichessInsightHub/

# Want to be able to read whole last segment "Lichess AppealbSystem" -- Question , is this an orthographic mistake with the "b" in between?

# Another orthographic mistake , 1. segment "About Lichess Insight Hub" , section 3 ,  "analysis"

**Comment by DakshHandeCode** [comment]
Could you please clear the message and provide some more detail about you're issue on the website @H0neymOOn

**Comment by DakshHandeCode** [comment]
You're issue have been fixed
